inherit_from: .rubocop_todo.yml

require:
  - rubocop-graphql
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
Style/RedundantAssignment:
  Enabled: false
