default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") { 'postgres' } %>
  username: <%= ENV.fetch("DATABASE_USER_NAME") { 'postgres' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'postgres' } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: budoman-backend_development

test:
  <<: *default
  database: budoman-backend_test

production:
  <<: *default
  database: budoman-backend_production
